### ISSUE TITLE
Obtain population of exit types from non-censored individuals

### ISSUE THREAD

**Issue by mikeguggis** [IDA-HumanCapital/fife#44]
LGBExitModeler currently obtains the population of exit types from the last observation from every individual. However, exit modeler only trains models for non-censored individuals. Thus if the exit type for censored individuals is different than non-censored individuals models will be fit including the exit type for censored individuals and produce near 0 probability forecasts. The population of exit types should be obtained from non-censored individuals. (IDA internal: JIRA issue FIFEEXTN-14)

**Comment by jay-dennis** [comment]
- forecasts is only predicting the state of exit for the last period, and is including all categories from exit types (e.g. no exit and 'nan').  This appears to trace to initialization of the LGBExitModeler ExitModeler's superclass StateModeler in base_modelers line 795 and line 655
- We should instead get the unique values of state_col for which the columns _duration = 0 and _event_observed = True
- I suggest overriding this by redefining self.num_class after line 795 and in line 730.  In order to do this on line 730 and not interfere with other functionality, I suggest creating a new variable self.class_values in the initialization of StateModeler around line 655 and overriding the value of this in the initialization of ExitModeler after line 795, then changing line 730 to call self.class_values.
- I implemented the solution as described above.

**Comment by jamesmckownbishop** [comment]
Thanks, Jay!
